# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-24 20:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_auto_20170224_2035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coord',
            old_name='longitute',
            new_name='longitude',
        ),
    ]
