# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-24 23:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0003_auto_20170224_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coord',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coords', to='routes.Route'),
        ),
    ]
