# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 21:58
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0004_auto_20170224_2310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coord',
            name='route',
        ),
        migrations.AddField(
            model_name='route',
            name='coords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=[], size=None),
        ),
        migrations.DeleteModel(
            name='Coord',
        ),
    ]
